from .manual_segmentation import ManualSegmentation
from .auto_segmentation import AutoSegmentation
from .zoom import Zoom
from .tool import Tool
from .move import Move
from .navigation import Navigation
from .figuras import Figuras
from .default import Default
from .toolBox import ToolBox
